spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  #tracing:
    #sampling:
      #probability: 1.0
    #propagation:
      #type: b3
  #zipkin:
    #tracing:
      #endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

logging:
  level:
    com.example.userservice.client: DEBUG



