spring:
  application:
    name: order-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.orderservice.client: DEBUG
  #pattern:
    #level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  #tracing:
    #sampling:
      #probability: 1.0
    #propagation:
      #type: b3
  #zipkin:
    #tracing:
      #endpoint: "http://localhost:9411/api/v2/spans"