spring:
  application:
    name: side-project
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false