spring:
  application:
    name: cart-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.cartservice.client: DEBUG